#The path to where the local backup files will be stored in.


automation:
  #Enable or disable the automatic backup system.
  enabled: true
  # This is the time span of when every backup will happen automatically.
  time-span:
    hour: 5
    minute: 30
    second: 0

services:
  selected: "local",
  local:
    backup-path: "backup/"
  google-drive:


#The list of paths that will be collected for backup.
target-paths: [
    "plugins/",
    "world/",
    "usercache.json",
    "banned-ips.json",
    "banned-players.json"
  ]

#List of files/folders that should be avoided. (Please do not remove session.lock)
files-blacklist: [
    "session.lock"
  ]