#The path to where the backup files will be stored in.
backup-path: "backup/"

automation:
  #Enable or disable the automatic backup system.
  enabled: true
  # This is the time span of when every backup will happen automatically.
  time-span:
    hour: 5
    minute: 30
    second: 0

#The list of paths that will be collected for backup.
target-paths: [
    "plugins/",
    "world/",
    "usercache.json",
    "banned-ips.json",
    "banned-players.json"
  ]

#List of paths that should be avoided. (Please do not remove session.lock)
files-blacklist: [
    "session.lock"
  ]